CODEOWNERS.txt
Add my github username to codeowners file.
=> add self to codeowners

CODEOWNERS.txt
Rhyn O adding username @Dissurender to the codeowners file.
=> Edit to codeowners file

CODEOWNERS.txt
Added my name to the co-owner list.
=> Add code owner

CODEOWNERS.txt
Added KINYUI1 to  CODEOWNERS file
=> added KINYUI1 to CODEOWNERS file

CODEOWNERS.txt
=> created a new branch to add name

CODEOWNERS.txt
adding myself to codeowners.txt
=> adding sohostory

Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserEntity.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserRepository.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserService.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserServiceImpl.java, Backend_Application/src/main/resources/application.properties, Backend_Application/target/classes/application.properties
Initialized file system "template" with User domain
=> added user domain and associated files

Frontend_Application/src/routes/register/register.component.jsx
=> registration bug fixed

Frontend_Application/src/routes/register/register.component.jsx
=> completed user registration validation

Frontend_Application/package.json, Frontend_Application/src/routes/register/register.component.jsx
When I pulled latest from main, there was a build error when running `npm run dev` resulting from a missing `axios` import and a missing `material ui` import 
pull changes in this branch, run `npm import`  and attempt to build the project, hopefully no errors occur from import issues.
=> adding missing imports to fix vite build

Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java
Implementing a way to auto-load users into the H2 database
=> adding bootstrap data file to initialize test users

Frontend_Application/src/routes/login/login.component.jsx, Frontend_Application/src/routes/register/register.component.jsx
created login validation to ensure that the username and password fields are checked before the user can select "login". User is unable to select the button if the fields are blank, validation also checks email format, and displays a snackbar if the information is incorrect. Also added a back button
=> created validation for login as well as added a back button to home

Frontend_Application/package-lock.json, Frontend_Application/package.json, Frontend_Application/src/routes/register/register.component.jsx
=> finalized the registration

Backend_Application/src/main/java/dsd/cohort/application/user/UserEntity.java
This is a simple code change to remove some redundant annotations in the UserEntity file.
=> removed redundant annotations and imports

Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java
Adding 3 secret users to the bootstrap data file.
=> 3 user entities bootstrapped

Backend_Application/src/main/java/dsd/cohort/application/Utils/Utility.java, Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserRequestDTO.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserService.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserServiceImpl.java
This is a very bare bones auth route for DEMO ONLY :small_red_triangle: 
Adds encryption functions with AES and compares without decryption.
=> add functionality for authenticating logins

Frontend_Application/src/routes/register/register.component.jsx
=> register working

Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeController.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeRepository.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeServiceImpl.java
Adding the functionality to search recipes by name partials.
=> recipe search by name impl

Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientController.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeController.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java
Adding the basis for the swagger ui docs to reflect http responses.
=> Springdoc annotations

Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java
Updating the bootstrapped users to have both encrypted passwords and valid passwords
=> passwords corrected

Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java, Frontend_Application/src/App.jsx, Frontend_Application/src/auth-context/AuthContext.jsx, Frontend_Application/src/auth-context/useAuth.jsx, Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/login/login.component.jsx
=> login user is now working with users from BootsrapData.java file

Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java
Merges didn't conflict but resulted in duplicate endpoints. Removed the old version.
=> Remove duplicate removefromgrocerylist endpoint

Backend_Application/src/main/java/dsd/cohort/application/Utils/Utility.java, Backend_Application/src/main/java/dsd/cohort/application/bootstrap/BootstrapData.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientController.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientEntity.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientService.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientServiceImpl.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeController.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeEntity.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeServiceImpl.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java
Summary: recipe-ingredient relationship was making a self-referencing loop.
- Changing Recipe-Ingredient to One-to-Many unidirectional
- Remove logic that could cause infinite recursion
- moved repository saves to be +1 scope from the appropriate methods for readability
=> Urgent fix to Recipe-Ingredient relationship

Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/mygrocerylist/mygrocerylist.component.jsx, Frontend_Application/src/routes/myrecipes/myrecipes.component.jsx
=> refactored page components to keep formatting consistent across app

Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeController.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeService.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeServiceImpl.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserController.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserService.java, Backend_Application/src/main/java/dsd/cohort/application/user/UserServiceImpl.java
Created an endpoint to help with the "results dropdown" for the user search bar.
Also included quick consolidation of the logic on createuser()
=> clean up createuser endpoint, add endpoint /recipes/names

Frontend_Application/src/App.jsx, Frontend_Application/src/components/MyRecipesCardContainer.component.jsx, Frontend_Application/src/components/recipe-card-container.component.jsx, Frontend_Application/src/components/recipe-card.component.jsx, Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/login/login.component.jsx, Frontend_Application/src/routes/mygrocerylist/mygrocerylist.component.jsx, Frontend_Application/src/routes/myrecipes/myrecipes.component.jsx, package.json
prop drilling last minute is a great idea!
=> added prop drilling and button function

Backend_Application/src/main/java/dsd/cohort/application/Utils/Utility.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientEntity.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeEntity.java, Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeServiceImpl.java
Fix for the SQL Error 23505: was doing the big dumb
=> recipe search working again

Frontend_Application/src/components/MyRecipesCardContainer.component.jsx, Frontend_Application/src/components/search-recipes-bar.component.jsx, Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/myrecipes/myrecipes.component.jsx
function is ready, but backend is not responding.
=> search bar function added

Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/login/login.component.jsx
=> dashboard functioning properly

Backend_Application/src/main/java/dsd/cohort/application/Utils/Utility.java, Backend_Application/src/main/java/dsd/cohort/application/ingredient/IngredientEntity.java, Frontend_Application/src/components/search-recipes-bar.component.jsx
Seeding autocomplete 'options' with api endpoint for recipe names
=> import, comment clean up. autocomplete component seeded

Frontend_Application/src/routes/dashboard/dashboard.component.jsx
someone removed set state from the dashboard.
=> adding missing setState

Frontend_Application/src/components/search-recipes-bar.component.jsx, Frontend_Application/src/routes/dashboard/dashboard.component.jsx
=> fixed the search function to display the result

LICENSE.txt, README.md, SETUPDOC.md
Here's some readme magic to get us started.
Please use this PR draft to discuss additions/changes
Things that need to be completed currently:
=> intitial readme, needs changes

Backend_Application/src/main/java/dsd/cohort/application/recipe/RecipeController.java, Frontend_Application/src/App.jsx, Frontend_Application/src/components/MyRecipesCardContainer.component.jsx, Frontend_Application/src/components/ingredient-card-container.component.jsx, Frontend_Application/src/components/ingredient-card.component.jsx, Frontend_Application/src/components/recipe-card-container.component.jsx, Frontend_Application/src/components/recipe-card.component.jsx, Frontend_Application/src/routes/dashboard/dashboard.component.jsx, Frontend_Application/src/routes/mygrocerylist/mygrocerylist.component.jsx, Frontend_Application/src/routes/myrecipes/myrecipes.component.jsx, Frontend_Application/src/routes/settings/settings.component.jsx
Final patches to get to demo status.
=> final commit
